### 心跳检测
GET http://localhost:8080/ping
Content-Type: application/json


### 用户登录
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "moocss@163.com",
    "password": "123456"
}

### 根据用户ID, 查询用户
GET http://localhost:8080/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTE4ODk2ODksIlVzZXJJRCI6MSwiVXNlckFnZW50IjoiQXBhY2hlLUh0dHBDbGllbnQvNC41LjEzIChKYXZhLzE3LjAuNikifQ.W2pAx3lvdFMsw29OspgTJsLQzMQhkFUgSZC3kMHXJtY

