// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"project-layout/internal/infra"
	"project-layout/internal/repository"
	"project-layout/internal/repository/cache"
	"project-layout/internal/repository/dao"
	"project-layout/internal/service"
	"project-layout/internal/web"
	"project-layout/internal/web/handler"
	"project-layout/pkg/ginx"
	"project-layout/pkg/log"
)

// Injectors from wire.go:

// wireApp init web application.
func wireApp(logger *log.Logger) (*ginx.HttpServer, func(), error) {
	db := infra.NewDB()
	client := infra.NewRDB()
	data, cleanup := infra.NewData(db, client, logger)
	userDAO := dao.NewUserDAO(data)
	userCache := cache.NewUserCache(data)
	userRepository := repository.NewUserRepository(userDAO, userCache, logger)
	userService := service.NewUserService(userRepository, logger)
	smsService := InitSmsService()
	codeCache := cache.NewCodeCache(data)
	codeRepository := repository.NewCodeRepository(codeCache)
	codeService := service.NewCodeService(smsService, codeRepository)
	userHandler := handler.NewUserHandler(userService, codeService, logger)
	router := web.NewRouter(userHandler)
	httpServer := InitWebServer(router)
	return httpServer, func() {
		cleanup()
	}, nil
}
