package model

import (
	"database/sql/driver"
)

type Model[E any] interface {
	TableName() string
	ToEntity() E      // Creates new Entity from ORM model.
	FromEntity(E) any // Creates new ORM model from Entity.

	Value() (driver.Value, error)   // Value returns driver Value from ORM model.
	Scan(any) error                 // Scan assigns a value from a database driver.
	MarshalBinary() ([]byte, error) // MarshalBinary marshals the receiver into a binary form and returns the result.
	UnmarshalBinary([]byte) error   // UnmarshalBinary unmarshals the receiver from a binary form generated by MarshalBinary.
}
